WPF upgrade
CnCNet/dta-mg-client-launcher pull request #11
Opened 2023-02-17 18:09 UTC by SadPencil

- WinForm has the layout issue which depends on system font and monitor DPI. Not easy to solve (although we can just increase the window size as a workaround).
- `MessageBox` is not a good tool to display an exception message due to missing scrollbars.
- No need to maintain two window for gpu message and missing component. One `AdvancedMessageBox` is enough.

Screenshots:
![01](https://user-images.githubusercontent.com/11227602/219743023-a6522bc9-2252-4ad5-8168-379da9260a6d.png)
![02](https://user-images.githubusercontent.com/11227602/219743053-08a422a1-5c14-406e-819f-81599e4457d4.png)
![03](https://user-images.githubusercontent.com/11227602/219743061-7b6b0716-a41c-4fb2-9e27-1f1f66af24bb.png)

2023-02-19 12:05 UTC, devo1929 approved these changes

2023-03-19 23:13 UTC, Rampastring requested changes

2023-03-19 23:13 UTC, Rampastring commented on CommandViewModel.cs
> +        get => text; set
Put the setter on its own line, looks weird to have it after the semicolon of the getter.

2023-03-19 23:13 UTC, Rampastring commented on CommandViewModel.cs
> +        get => command; set
Same here as above.

2023-03-19 23:13 UTC, Rampastring commented on Program.cs
> +                "The client has detected an incompatibility between your graphics card and the DirectX11 and OpenGL versions of the CnCNet client.\n\n" +
This line is much longer than the lines below, making the message excessively wide and its layout weird. Split it from the middle, like the line below.

2023-03-20 04:18 UTC, SadPencil commented
![Snipaste_2023-03-20_12-17-48](https://user-images.githubusercontent.com/11227602/226246115-c0f2625e-d42a-4ef9-8da2-855d1903ad45.png)
Updated

2023-03-21 21:43 UTC, Metadorius commented
> ![Snipaste_2023-03-20_12-17-48](https://user-images.githubusercontent.com/11227602/226246115-c0f2625e-d42a-4ef9-8da2-855d1903ad45.png) Updated


1) What does this even mean? 
![image](https://user-images.githubusercontent.com/17500545/226748009-565c1a40-ab34-4feb-a637-d27b7ec28e56.png)
2) If there's an incompatibility between PC and DX11 version, why is this an option?
![image](https://user-images.githubusercontent.com/17500545/226748115-99a272aa-948a-4dcd-98b8-3fb6fbc1d461.png)

2023-03-22 06:36 UTC, SadPencil commented
@Metadorius 
> What does this even mean?

This dialog is launched by the dialog test, because it is hard to reproduce the incompatibility just in order to show the prompt. The only difference is the dialog launched by the dialog test will not do anything and has a `(All buttons here won't work)` text.

> If there's an incompatibility between PC and DX11 version, why is this an option?

This PR only migrates the project from WinForm to WPF. No texts or buttons are changed.
Besides, `Alternatively, you can retry launching the DirectX11 version of the client.`

2023-03-22 10:30 UTC, Metadorius requested changes

2023-03-22 10:30 UTC, Metadorius commented on RelayCommand.cs
> +    }
This begs for expression bodies.

2023-03-22 10:30 UTC, Metadorius commented on Program.cs
> +                }),
Unnecessary lambda brackets here.

2023-03-22 10:30 UTC, Metadorius commented on Program.cs
> +        }
```suggestion

        if (dialogResult)
            OpenUri(downloadLink);
```

2023-03-22 10:30 UTC, Metadorius commented on AdvancedMessageBoxHelper.cs
> +            });
1. The purpose of `i_copy` is unobvious for those who don't know about capture issues in C# (I didn't and had to guess and google for example).
2. Naming violation.

```suggestion
            // passing just i to the lambda will not work as
            // intended due to C# variable capture specifics
            int iCaptured = i;
            commands.Add(new CommandViewModel()
            {
                Text = selections[i],
                Command = new RelayCommand(_ =>
                {
                    msgbox.Result = iCaptured;
                    msgbox.Close();
                }),
            });
```

2023-03-22 10:30 UTC, Metadorius commented on NotifyPropertyChangedBase.cs
I recommend to use ReactiveUI.Fody for autogenerating INPC boilerplate.

2023-03-22 14:27 UTC, SadPencil commented on NotifyPropertyChangedBase.cs
This requires distributing a DLL where launcher is supposed single-file contained

2023-03-24 20:21 UTC, merged